//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.piik.app.service;

import android.content.Context;
import android.location.LocationManager;

public final class LocationService_
    extends LocationService
{

    private Context context_;

    private LocationService_(Context context) {
        context_ = context;
        init_();
    }

    public static LocationService_ getInstance_(Context context) {
        return new LocationService_(context);
    }

    private void init_() {
        locationManager = ((LocationManager) context_.getSystemService(Context.LOCATION_SERVICE));
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
