//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.piik.app;

import android.content.Context;

public final class ActivityLauncher_
    extends ActivityLauncher
{

    private Context context_;

    private ActivityLauncher_(Context context) {
        context_ = context;
        init_();
    }

    public static ActivityLauncher_ getInstance_(Context context) {
        return new ActivityLauncher_(context);
    }

    private void init_() {
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
