//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.piik.app.rest;

import java.util.HashMap;
import com.piik.app.model.PlacesList;
import org.androidannotations.api.rest.RestErrorHandler;
import org.springframework.http.HttpMethod;
import org.springframework.http.converter.json.GsonHttpMessageConverter;
import org.springframework.web.client.RestClientException;
import org.springframework.web.client.RestTemplate;

public final class PlacesRestClient_
    implements PlacesRestClient
{

    private String rootUrl;
    private RestTemplate restTemplate;
    private RestErrorHandler restErrorHandler;

    public PlacesRestClient_() {
        rootUrl = "http://80.240.137.139:8080/api";
        restTemplate = new RestTemplate();
        restTemplate.getMessageConverters().add(new GsonHttpMessageConverter());
    }

    @Override
    public PlacesList findPlacesNearByLocation(double lat, double lon) {
        HashMap<String, Object> urlVariables = new HashMap<String, Object>();
        urlVariables.put("lon", lon);
        urlVariables.put("lat", lat);
        try {
            return restTemplate.exchange(rootUrl.concat("/places?lat={lat}&lon={lon}"), HttpMethod.GET, null, PlacesList.class, urlVariables).getBody();
        } catch (RestClientException e) {
            if (restErrorHandler!= null) {
                restErrorHandler.onRestClientExceptionThrown(e);
                return null;
            } else {
                throw e;
            }
        }
    }

}
